# Generated by Django 3.0.5 on 2020-08-09 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200804_0600'),
        ('users', '0002_auto_20200808_1354'),
    ]

    operations = [
    ]
