# Generated by Django 3.0.5 on 2020-08-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200804_0600'),
        ('content', '0003_auto_20200805_0814'),
    ]

    operations = [
    ]
